// include/common/ticket.h
#ifndef TICKET_H
#define TICKET_H

#include <string>
#include <chrono>
#include <nlohmann/json.hpp>

using json = nlohmann::json;

/**
 * @brief Represents a transport ticket
 * 
 * As per requirements, ticket contains:
 * - Ticket ID (generated by the Back-Office)
 * - Creation Date
 * - Validity in Days
 * - Line Number (Geographical validity)
 */
class Ticket {
public:
    // Constructors
    Ticket();
    Ticket(const std::string& id, int validityDays, int lineNumber);
    
    // Getters
    std::string getId() const { return ticketId_; }
    std::string getCreationDate() const { return creationDate_; }
    int getValidityDays() const { return validityDays_; }
    int getLineNumber() const { return lineNumber_; }
    
    // Setters
    void setId(const std::string& id) { ticketId_ = id; }
    void setCreationDate(const std::string& date) { creationDate_ = date; }
    void setValidityDays(int days) { validityDays_ = days; }
    void setLineNumber(int line) { lineNumber_ = line; }
    
    // Validation methods
    bool isValid() const;
    bool isExpired() const;
    
    // Serialization to/from JSON
    std::string toJson() const;
    static Ticket fromJson(const std::string& jsonStr);
    
    // Base64 serialization (as required by task)
    std::string toBase64() const;
    static Ticket fromBase64(const std::string& base64Str);
    
    // For nlohmann::json automatic conversion
    friend void to_json(json& j, const Ticket& t);
    friend void from_json(const json& j, Ticket& t);

private:
    std::string ticketId_;
    std::string creationDate_;  // ISO 8601 format: YYYY-MM-DDTHH:MM:SS
    int validityDays_;
    int lineNumber_;
    
    // Helper functions
    std::chrono::system_clock::time_point getCreationTimePoint() const;
    static std::string getCurrentDateISO();
    
    // Base64 encoding/decoding helpers
    static std::string base64Encode(const std::string& input);
    static std::string base64Decode(const std::string& input);
};

#endif // TICKET_H
